/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Test */

#ifndef _Included_org_example_Test
#define _Included_org_example_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Test
 * Method:    getArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_example_Test_getArray
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
